[theme]
primaryColor='#F63366'
backgroundColor='#FFFFFF'
secondaryBackgroundColor='#F0F2F6'
textColor='#262730'
font='sans serif'

[browser]
gatherUsageStats=false

[server]
port=8080
address='0.0.0.0'